import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import Banner from '../Components/Banner';
import Espacialty from '../Components/Espacialty';
import Footer from '../Components/Footer';
import Form from '../Components/Form';
import Header from '../Components/Header';
import Product from '../Components/Product';
import loading from './loading.gif';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 2500);
  }, []);

  return (
    <div>
      <Head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Modial food | Accueil </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/mixitup/3.3.1/mixitup.min.js"
          defer></script>
           <script src="https://unpkg.com/scrollreveal" defer></script>
      </Head>

      {isLoading && (
        <div className='load'>
          <Image src={loading} alt="" />
        </div>
      )}

      <Header />

      <main>

        <Banner/>
        <Espacialty />
        <Product />
        <Form />
      </main>
      <Footer />
    </div>
  );
}
